!!python/object:argparse.Namespace
attr: attributes.yaml
b1: 0.5
b2: 0.999
batch_size: 4
config: config.yaml
cycle_consistency: true
data: [PATH_TO_DATA]
dataset: celeba-hq
gamma: 0.1
gpu: true
image_size: 256
interpolation_regularize: true
iterD: 1
iterG: 1
l1: 10.0
l2: 10.0
l3: 1.0
l4: 0.000001
load: null
log_interval: 100
lr: 5.0e-05
multi_gpu: false
name: null
orthogonal_regularize: true
repeat_G: 6
sample_interval: 1000
save: model/weights.pth
save_interval: 2000
start_step: 0
steps: 200000
zero_consistency: true